# Generated by Django 4.2.16 on 2024-09-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bus',
            name='frequency',
        ),
        migrations.AddField(
            model_name='bus',
            name='frequency',
            field=models.ManyToManyField(to='reservations.day'),
        ),
    ]
